package com.hospital.service;

import com.hospital.algorithms.WaitTimePredictor.Prediction;
import com.hospital.model.Alert;
import com.hospital.model.AlertSeverity;
import com.hospital.model.Bed;
import com.hospital.model.BedStatus;
import com.hospital.model.Doctor;
import com.hospital.model.Patient;
import com.hospital.model.Permission;
import com.hospital.model.StaffUser;
import com.hospital.persistence.DataAccessException;
import com.hospital.persistence.dao.AdmissionLogDAO.LogEntry;
import com.hospital.service.AnalyticsSnapshot.DoctorLoad;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.AccessDeniedException;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;

/**
 * Read-only reporting on top of {@link HospitalManager}: the plain-text shift handover report
 * and CSV exports of patients and the audit trail.
 * <p>
 * Exports require {@link Permission#EXPORT_REPORTS}. CSV files follow RFC 4180 (CRLF line ends,
 * quoted fields) and start with a UTF-8 byte-order mark so Excel shows accented names correctly.
 * Free-text cells are protected against spreadsheet formula injection (see {@link #csvEscape}).
 */
public class ReportService {

    /** Maximum line length of the text report; fits a portrait page at 9 pt monospace. */
    public static final int REPORT_WIDTH = 100;

    public static final List<String> PATIENT_COLUMNS = List.of(
            "id", "mrn", "full_name", "age", "gender", "category", "chief_complaint", "trauma",
            "esi_level", "severity_score", "priority_score", "status", "bed_id", "doctor",
            "intake_time", "admitted_time", "discharged_time", "wait_minutes");

    public static final List<String> ACTIVITY_COLUMNS = List.of(
            "id", "time", "action", "patient_id", "patient_mrn", "patient_name", "bed_id", "doctor",
            "priority_score", "performed_by", "details");

    private static final int MAX_CRITICAL_ALERTS = 10;
    private static final int RECENT_ACTIVITY_ROWS = 15;
    private static final String UTF8_BOM = "﻿";
    private static final String CRLF = "\r\n";
    /** Leading characters that make Excel / LibreOffice treat a cell as a formula. */
    private static final String FORMULA_PREFIXES = "=+-@\t\r";

    private static final DateTimeFormatter HEADER_TIME = DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm", Locale.ENGLISH);
    private static final DateTimeFormatter ROW_TIME = DateTimeFormatter.ofPattern("dd MMM HH:mm", Locale.ENGLISH);
    private static final DateTimeFormatter CSV_TIME = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss", Locale.ROOT);

    private final HospitalManager manager;

    public ReportService(HospitalManager manager) {
        this.manager = Objects.requireNonNull(manager, "manager");
    }

    // =====================================================================
    // Shift handover report
    // =====================================================================

    /**
     * Plain-text handover report with fixed-width columns (at most {@link #REPORT_WIDTH} characters per line).
     * All relative times ("waited", "in bed") are measured against the hospital clock {@code manager.now()}.
     */
    public String shiftHandoverReport() {
        LocalDateTime now = manager.now();
        StringBuilder out = new StringBuilder(8_192);
        header(out, now);
        summary(out);
        waitingQueue(out, now);
        admittedPatients(out, now);
        bedsNeedingAttention(out, now);
        doctorWorkload(out);
        criticalAlerts(out);
        recentActivity(out);
        out.append(rule('=')).append('\n');
        out.append(center("END OF REPORT")).append('\n');
        return out.toString();
    }

    private void header(StringBuilder out, LocalDateTime now) {
        out.append(rule('=')).append('\n');
        out.append(center("EMERGENCY DEPARTMENT - SHIFT HANDOVER REPORT")).append('\n');
        out.append(rule('=')).append('\n');

        long offset = manager.clockOffset().toMinutes();
        String generatedAt = now.format(HEADER_TIME) + (offset > 0 ? "  (simulation clock +" + duration(offset) + ")" : "");
        StaffUser user = manager.currentUser();
        String generatedBy = user == null ? "-" : user.getFullName() + " (" + user.getRole().getDisplayName() + ")";
        out.append(field("Generated at", generatedAt));
        out.append(field("Generated by", generatedBy));
        out.append(field("Database", manager.databaseDescription()));
        out.append('\n');
    }

    private static String field(String label, String value) {
        return String.format("%-13s: %s\n", label, fit(value, REPORT_WIDTH - 15));
    }

    private void summary(StringBuilder out) {
        AnalyticsSnapshot a = manager.analytics();
        int admitted = manager.admittedPatients().size();
        section(out, "SUMMARY");
        summaryRow(out, "Patients waiting", String.valueOf(a.waitingCount()),
                "Beds available", a.bedsAvailable() + " / " + a.bedsTotal());
        summaryRow(out, "Critical waiting (ESI 1-2)", String.valueOf(a.criticalWaitingCount()),
                "Bed occupancy", String.format(Locale.ROOT, "%.0f%%", a.occupancyRate() * 100));
        summaryRow(out, "Overdue (past ESI target)", String.valueOf(a.overdueCount()),
                "Doctors available / on duty", a.doctorsAvailable() + " / " + a.doctorsOnDuty());
        summaryRow(out, "Longest wait", a.waitingCount() == 0 ? "-" : duration(a.longestWaitMinutes()),
                "Avg door-to-bed (admitted)", admitted > 0 ? duration(Math.round(a.averageDoorToBedMinutes())) : "-");
        summaryRow(out, "Patients admitted", String.valueOf(admitted),
                "Unacknowledged alerts", String.valueOf(manager.unacknowledgedAlertCount()));
        out.append('\n');
    }

    private static void summaryRow(StringBuilder out, String label1, String value1, String label2, String value2) {
        out.append(String.format("  %-27s: %-16s %-28s: %s", label1, fit(value1, 16), label2, fit(value2, 22)))
                .append('\n');
    }

    private void waitingQueue(StringBuilder out, LocalDateTime now) {
        List<Patient> waiting = manager.waitingQueue();
        Map<Integer, Prediction> predictions = safePredictions();
        section(out, "WAITING QUEUE (" + count(waiting.size(), "patient") + ", highest priority first)");
        if (waiting.isEmpty()) {
            none(out);
            return;
        }
        String fmt = "  %3s %-5s %-20s %-7s %-24s %7s %6s %-7s %8s\n";
        out.append(line(fmt, "#", "ESI", "Patient", "Age/Sex", "Complaint", "Waited", "Target", "Flag", "Bed ETA"));
        int rank = 1;
        for (Patient p : waiting) {
            int target = p.getTriageLevel() == null ? 0 : p.getTriageLevel().getTargetWaitMinutes();
            out.append(line(fmt, rank++, esi(p), fit(p.getFullName(), 20), ageSex(p), fit(p.getChiefComplaint(), 24),
                    duration(p.waitingMinutes(now)), target == 0 ? "now" : duration(target),
                    p.isOverdue(now) ? "OVERDUE" : "", predicted(predictions.get(p.getId()))));
        }
        out.append('\n');
    }

    /** Wait predictions are a nice-to-have: a predictor failure must not stop the handover report. */
    private Map<Integer, Prediction> safePredictions() {
        try {
            Map<Integer, Prediction> predictions = manager.predictWaits();
            return predictions == null ? Map.of() : predictions;
        } catch (RuntimeException e) {
            return Map.of();
        }
    }

    private static String predicted(Prediction p) {
        if (p == null) return "-";
        if (p.noBedPossible()) return "no bed";
        return p.minutesUntilBed() <= 0 ? "now" : duration(p.minutesUntilBed());
    }

    private void admittedPatients(StringBuilder out, LocalDateTime now) {
        List<Patient> admitted = new ArrayList<>(manager.admittedPatients());
        admitted.sort(Comparator.comparing((Patient p) -> p.getAssignedBedId() == null ? "" : p.getAssignedBedId())
                .thenComparingInt(Patient::getId));
        section(out, "ADMITTED PATIENTS (" + count(admitted.size(), "patient") + ", by bed)");
        if (admitted.isEmpty()) {
            none(out);
            return;
        }
        String fmt = "  %-8s %-20s %-5s %-21s %-26s %7s\n";
        out.append(line(fmt, "Bed", "Patient", "ESI", "Doctor", "Complaint", "In bed"));
        for (Patient p : admitted) {
            Doctor d = manager.findDoctor(p.getAssignedDoctorId());
            String inBed = p.getAdmittedTime() == null ? "-" : duration(minutesBetween(p.getAdmittedTime(), now));
            out.append(line(fmt, fit(p.getAssignedBedId(), 8), fit(p.getFullName(), 20), esi(p),
                    d == null ? "UNASSIGNED" : fit(d.getName(), 21), fit(p.getChiefComplaint(), 26), inBed));
        }
        out.append('\n');
    }

    private void bedsNeedingAttention(StringBuilder out, LocalDateTime now) {
        List<Bed> attention = new ArrayList<>();
        int cleaning = 0;
        for (Bed b : manager.allBeds()) {
            if (b.getStatus() == BedStatus.CLEANING) cleaning++;
            if (b.getStatus() == BedStatus.CLEANING || b.getStatus() == BedStatus.MAINTENANCE) attention.add(b);
        }
        attention.sort(Comparator.comparing(Bed::getBedId));
        section(out, "BEDS NEEDING ATTENTION (" + cleaning + " cleaning, " + (attention.size() - cleaning) + " maintenance)");
        if (attention.isEmpty()) {
            none(out);
            return;
        }
        String fmt = "  %-8s %-22s %-30s %-11s %8s\n";
        out.append(line(fmt, "Bed", "Type", "Ward", "Status", "For"));
        for (Bed b : attention) {
            String since = b.getUpdatedAt() == null ? "-" : duration(minutesBetween(b.getUpdatedAt(), now));
            out.append(line(fmt, fit(b.getBedId(), 8), fit(b.getType().getDisplayName(), 22),
                    fit(b.getWardName(), 30), b.getStatus().name(), since));
        }
        out.append('\n');
    }

    private void doctorWorkload(StringBuilder out) {
        List<DoctorLoad> loads = manager.analytics().doctorLoads();
        section(out, "DOCTOR WORKLOAD (busiest first)");
        if (loads.isEmpty()) {
            none(out);
            return;
        }
        String fmt = "  %-22s %-22s %-8s %-12s %s\n";
        out.append(line(fmt, "Doctor", "Specialty", "Patients", "Load", "Status"));
        for (DoctorLoad l : loads) {
            String status = !l.onDuty() ? "OFF DUTY" : l.active() >= l.max() ? "AT CAPACITY" : l.active() > 0 ? "BUSY" : "AVAILABLE";
            out.append(line(fmt, fit(l.name(), 22), fit(l.specialty(), 22), l.active() + " / " + l.max(),
                    loadBar(l.active(), l.max()), status));
        }
        out.append('\n');
    }

    /** Ten-character text gauge, e.g. {@code [######    ]}. */
    static String loadBar(int active, int max) {
        int filled = max <= 0 ? 10 : (int) Math.round(10.0 * Math.min(active, max) / max);
        return "[" + "#".repeat(filled) + " ".repeat(10 - filled) + "]";
    }

    private void criticalAlerts(StringBuilder out) {
        List<Alert> critical = manager.recentAlerts().stream()
                .filter(a -> !a.isAcknowledged() && a.getSeverity() == AlertSeverity.CRITICAL)
                .toList();
        section(out, "UNACKNOWLEDGED CRITICAL ALERTS (" + critical.size() + ", newest first)");
        if (critical.isEmpty()) {
            none(out);
            return;
        }
        String fmt = "  %-12s %-20s %s\n";
        out.append(line(fmt, "Time", "Category", "Message"));
        for (Alert a : critical.subList(0, Math.min(MAX_CRITICAL_ALERTS, critical.size()))) {
            out.append(line(fmt, a.getCreatedAt() == null ? "-" : a.getCreatedAt().format(ROW_TIME),
                    fit(a.getCategory().name().replace('_', ' '), 20), fit(a.getMessage(), REPORT_WIDTH - 36)));
        }
        if (critical.size() > MAX_CRITICAL_ALERTS) {
            out.append("  ... and ").append(critical.size() - MAX_CRITICAL_ALERTS)
                    .append(" more - see the Alerts screen\n");
        }
        out.append('\n');
    }

    private void recentActivity(StringBuilder out) {
        List<LogEntry> entries = manager.recentActivity(RECENT_ACTIVITY_ROWS);
        section(out, "RECENT ACTIVITY (last " + RECENT_ACTIVITY_ROWS + ", newest first)");
        if (entries.isEmpty()) {
            none(out);
            return;
        }
        Map<Integer, Patient> patientCache = new HashMap<>();
        String fmt = "  %-12s %-11s %-18s %-8s %-11s %s\n";
        out.append(line(fmt, "Time", "Action", "Patient", "Bed", "By", "Details"));
        for (LogEntry e : entries) {
            Patient p = lookupPatient(e.patientId(), patientCache);
            out.append(line(fmt, e.createdAt() == null ? "-" : e.createdAt().format(ROW_TIME), shortAction(e.action()),
                    fit(p == null ? "#" + e.patientId() : p.getFullName(), 18), fit(orDash(e.bedId()), 8),
                    fit(orDash(e.performedBy()), 11), fit(orDash(e.details()), REPORT_WIDTH - 67)));
        }
        out.append('\n');
    }

    private static String shortAction(String action) {
        if (action == null) return "-";
        return "LEFT_WITHOUT_BEING_SEEN".equals(action) ? "LWBS" : fit(action, 11);
    }

    // =====================================================================
    // File exports
    // =====================================================================

    /** Writes {@link #shiftHandoverReport()} as UTF-8 text with the platform's line endings. */
    public OperationResult saveShiftReport(Path file) {
        OperationResult refused = checkExport(file);
        if (refused != null) return refused;
        try {
            String report = shiftHandoverReport();
            Files.writeString(file, report.replace("\n", System.lineSeparator()), StandardCharsets.UTF_8);
            return OperationResult.ok("Exported shift report (" + report.lines().count() + " lines) to " + fileName(file));
        } catch (IOException e) {
            return writeFailed(file, e);
        } catch (DataAccessException e) {
            return OperationResult.fail("Could not build the report: " + e.getMessage());
        }
    }

    /**
     * Every patient ever registered, one row each. {@code wait_minutes} is the time spent in the waiting room:
     * intake to admission for patients who were admitted (including those discharged since), intake to the
     * time they left for patients who left without being seen, and intake to now for patients still waiting.
     */
    public OperationResult exportPatientsCsv(Path file) {
        OperationResult refused = checkExport(file);
        if (refused != null) return refused;
        try {
            LocalDateTime now = manager.now();
            List<Patient> patients = manager.allPatientRecords();
            StringBuilder csv = csvHeader(PATIENT_COLUMNS);
            for (Patient p : patients) {
                Doctor d = manager.findDoctor(p.getAssignedDoctorId());
                csvRow(csv,
                        number(p.getId()),
                        text(p.getMrn()),
                        text(p.getFullName()),
                        number(p.getAge()),
                        text(p.getGender()),
                        text(p.getCategory()),
                        text(p.getChiefComplaint()),
                        p.isTrauma() ? "yes" : "no",
                        p.getTriageLevel() == null ? "" : number(p.getTriageLevel().getEsi()),
                        decimal(p.getSeverityScore(), 1),
                        decimal(p.getPriorityScore(), 2),
                        p.getStatus() == null ? "" : text(p.getStatus().name()),
                        text(p.getAssignedBedId()),
                        text(d == null ? null : d.getName()),
                        timestamp(p.getIntakeTime()),
                        timestamp(p.getAdmittedTime()),
                        timestamp(p.getDischargedTime()),
                        number(waitMinutes(p, now)));
            }
            Files.writeString(file, csv.toString(), StandardCharsets.UTF_8);
            return OperationResult.ok("Exported " + patients.size() + " rows to " + fileName(file));
        } catch (IOException e) {
            return writeFailed(file, e);
        } catch (DataAccessException e) {
            return OperationResult.fail("Could not read patient records: " + e.getMessage());
        }
    }

    /** Minutes in the waiting room: intake until admission, until leaving unseen, or until now (still waiting). */
    static long waitMinutes(Patient p, LocalDateTime now) {
        if (p.getIntakeTime() == null) return 0;
        LocalDateTime end = p.getAdmittedTime() != null ? p.getAdmittedTime()
                : p.getDischargedTime() != null ? p.getDischargedTime() : now;
        return minutesBetween(p.getIntakeTime(), end);
    }

    /** The newest {@code limit} audit entries, written oldest first so the file reads chronologically. */
    public OperationResult exportActivityCsv(Path file, int limit) {
        OperationResult refused = checkExport(file);
        if (refused != null) return refused;
        if (limit < 1) return OperationResult.fail("Choose at least one activity row to export.");
        try {
            List<LogEntry> entries = new ArrayList<>(manager.recentActivity(limit));
            entries.sort(Comparator.comparingInt(LogEntry::id));
            Map<Integer, Patient> patientCache = new HashMap<>();
            StringBuilder csv = csvHeader(ACTIVITY_COLUMNS);
            for (LogEntry e : entries) {
                Patient p = lookupPatient(e.patientId(), patientCache);
                Doctor d = manager.findDoctor(e.doctorId());
                csvRow(csv,
                        number(e.id()),
                        timestamp(e.createdAt()),
                        text(e.action()),
                        number(e.patientId()),
                        text(p == null ? null : p.getMrn()),
                        text(p == null ? null : p.getFullName()),
                        text(e.bedId()),
                        text(d == null ? null : d.getName()),
                        e.priorityScore() == null ? "" : decimal(e.priorityScore(), 2),
                        text(e.performedBy()),
                        text(e.details()));
            }
            Files.writeString(file, csv.toString(), StandardCharsets.UTF_8);
            return OperationResult.ok("Exported " + entries.size() + " rows to " + fileName(file));
        } catch (IOException e) {
            return writeFailed(file, e);
        } catch (DataAccessException e) {
            return OperationResult.fail("Could not read the activity log: " + e.getMessage());
        }
    }

    /** Null when the export may go ahead, otherwise the failure to return. Nothing is written on refusal. */
    private OperationResult checkExport(Path file) {
        if (!manager.hasPermission(Permission.EXPORT_REPORTS)) {
            StaffUser u = manager.currentUser();
            if (u == null) return OperationResult.fail("Permission denied: please log in first.");
            return OperationResult.fail("Permission denied: a " + u.getRole().getDisplayName().toLowerCase(Locale.ROOT)
                    + " account cannot " + Permission.EXPORT_REPORTS.getDescription().toLowerCase(Locale.ROOT) + ".");
        }
        if (file == null) return OperationResult.fail("No file was chosen.");
        return null;
    }

    private static OperationResult writeFailed(Path file, IOException e) {
        String reason;
        if (e instanceof NoSuchFileException) reason = "the folder does not exist";
        else if (e instanceof AccessDeniedException) reason = "access denied (is the file open in another program?)";
        else reason = e.getMessage() == null ? e.getClass().getSimpleName() : e.getMessage();
        return OperationResult.fail("Could not write " + fileName(file) + ": " + reason + ".");
    }

    private static String fileName(Path file) {
        return file.getFileName() == null ? file.toString() : file.getFileName().toString();
    }

    private Patient lookupPatient(int patientId, Map<Integer, Patient> cache) {
        if (cache.containsKey(patientId)) return cache.get(patientId);
        Patient p = manager.findPatientRecord(patientId).orElse(null);
        cache.put(patientId, p);
        return p;
    }

    // =====================================================================
    // CSV helpers
    // =====================================================================

    /**
     * Escapes one free-text CSV cell: RFC 4180 quoting plus formula-injection protection.
     * Equivalent to {@code csvEscape(value, true)}.
     */
    public static String csvEscape(String value) {
        return csvEscape(value, true);
    }

    /**
     * Escapes one CSV cell. {@code null} becomes an empty cell. A value containing a comma, double quote,
     * CR or LF is wrapped in double quotes with embedded quotes doubled (RFC 4180).
     * When {@code freeText} is true, a value starting with {@code = + - @}, TAB or CR is prefixed with an
     * apostrophe so a spreadsheet shows it as text instead of evaluating it (CSV/formula injection).
     * Numeric columns pass {@code false} so negative numbers stay numbers.
     */
    public static String csvEscape(String value, boolean freeText) {
        if (value == null) return "";
        String v = value;
        if (freeText && !v.isEmpty() && FORMULA_PREFIXES.indexOf(v.charAt(0)) >= 0) v = "'" + v;
        boolean quote = v.indexOf(',') >= 0 || v.indexOf('"') >= 0 || v.indexOf('\r') >= 0 || v.indexOf('\n') >= 0;
        return quote ? '"' + v.replace("\"", "\"\"") + '"' : v;
    }

    private static StringBuilder csvHeader(List<String> columns) {
        StringBuilder csv = new StringBuilder(16_384).append(UTF8_BOM);
        csv.append(String.join(",", columns)).append(CRLF);
        return csv;
    }

    /** Appends one row; every cell must already be escaped. */
    private static void csvRow(StringBuilder csv, String... cells) {
        csv.append(String.join(",", cells)).append(CRLF);
    }

    private static String text(String value) { return csvEscape(value, true); }

    private static String number(long value) { return Long.toString(value); }

    private static String decimal(double value, int places) {
        return String.format(Locale.ROOT, "%." + places + "f", value);
    }

    private static String timestamp(LocalDateTime t) { return t == null ? "" : t.format(CSV_TIME); }

    // =====================================================================
    // Text helpers
    // =====================================================================

    /**
     * Splits report text into pages of at most {@code linesPerPage} lines (used for printing).
     * A section heading is kept with its underline and first two lines (moved to the next page
     * rather than stranded at the bottom). Always returns at least one page.
     */
    public static List<List<String>> paginate(String text, int linesPerPage) {
        int perPage = Math.max(1, linesPerPage);
        List<String> lines = text == null || text.isEmpty() ? List.of() : text.lines().toList();
        List<List<String>> pages = new ArrayList<>();
        int start = 0;
        while (start < lines.size()) {
            int end = Math.min(lines.size(), start + perPage);
            if (end < lines.size()) {
                // a rule at end-2..end means the heading above it would be cut from its table
                for (int k = end - 2; k <= end; k++) {
                    if (k - 1 > start && isRule(lines.get(k))) {
                        end = k - 1;
                        break;
                    }
                }
            }
            pages.add(lines.subList(start, end));
            start = end;
        }
        if (pages.isEmpty()) pages.add(List.of());
        return pages;
    }

    private static boolean isRule(String line) {
        return line.length() >= 20 && (line.chars().allMatch(c -> c == '-') || line.chars().allMatch(c -> c == '='));
    }

    /** Single-line, at most {@code width} characters; longer text ends in "...". */
    static String fit(String s, int width) {
        String clean = s == null ? "" : s.replaceAll("[\\r\\n\\t]+", " ").strip();
        if (clean.length() <= width) return clean;
        return width <= 3 ? clean.substring(0, width) : clean.substring(0, width - 3) + "...";
    }

    /** Compact duration that fits a 7-character column: "45m", "2h 05m", "3d 04h". */
    static String duration(long minutes) {
        long m = Math.max(0, minutes);
        if (m < 60) return m + "m";
        if (m < 24 * 60) return String.format(Locale.ROOT, "%dh %02dm", m / 60, m % 60);
        return String.format(Locale.ROOT, "%dd %02dh", m / (24 * 60), (m / 60) % 24);
    }

    private static long minutesBetween(LocalDateTime from, LocalDateTime to) {
        return Math.max(0, Duration.between(from, to).toMinutes());
    }

    private static String line(String format, Object... args) {
        return String.format(Locale.ROOT, format, args);
    }

    private static void section(StringBuilder out, String title) {
        out.append(fit(title, REPORT_WIDTH)).append('\n').append(rule('-')).append('\n');
    }

    private static void none(StringBuilder out) {
        out.append("  (none)\n\n");
    }

    private static String rule(char c) {
        return String.valueOf(c).repeat(REPORT_WIDTH);
    }

    private static String center(String title) {
        return " ".repeat(Math.max(0, (REPORT_WIDTH - title.length()) / 2)) + title;
    }

    private static String count(int n, String noun) {
        return n + " " + noun + (n == 1 ? "" : "s");
    }

    private static String esi(Patient p) {
        return p.getTriageLevel() == null ? "-" : "ESI " + p.getTriageLevel().getEsi();
    }

    private static String ageSex(Patient p) {
        String g = p.getGender() == null || p.getGender().isEmpty() ? "?" : p.getGender().substring(0, 1);
        return p.getAge() + "/" + g;
    }

    private static String orDash(String s) {
        return s == null || s.isBlank() ? "-" : s;
    }
}
